### ISSUE TITLE
StackOverflow when adding two AVLTreeDigest

### ISSUE THREAD

**Issue by guillaumepitel** [tdunning/t-digest#125]
I have a long running dstributed application that computes various information on the web graph. I store a digest of some values in a AVLTreeDigest, and sometimes I need to collect all digests, so I need to add them all. And this happened :
`2019-04-09 16:20:19,113 82839181 ERROR [grizzly-http-server-8] c.e.w.b.LogarithmicStatistics - Error while trying to add 3.000e-13[0.0],1.231e-06[1.0] to 3.000e-13[0.0],3.002e-13[0.5],3.033e-13[0.75],3.127e-13[0.9],3.380e-13[0.95],4.338e-13[0.975],6.264e-13[0.987],1.219e-12[0.995],6.652e-08[1.0]
java.lang.StackOverflowError: null
        at com.tdunning.math.stats.AVLGroupTree.add(AVLGroupTree.java:159)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:98)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
        at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:156)
        at com.tdunning.math.stats.AVLTreeDigest.compress(AVLTreeDigest.java:186)
` 

This happens probably because the histogram on which add() is called is empty.

**Comment by tdunning** [comment]
Do you have information about which version you are running?

**Comment by guillaumepitel** [comment]
Latest (3.2)

**Comment by tdunning** [comment]
@guillaumepitel Do you have any further information about this problem?

Were you able to switch to MergingDigest or to head and solve the problem?

I would like to decide whether this is a blocker for a 3.3 release (or an incentive!)

**Comment by guillaumepitel** [comment]
Hi @tdunning unfortunately, I couldn't make it work, so we decided to use another solution in the meantime. Sorry that's not very helpful.
