### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by KayBeSee** [tdunning/t-digest#126]
I am trying to build this but I am getting failures on the tests. It looks like the failures were introduced in this commit: https://github.com/tdunning/t-digest/commit/48c8d56456ff92875d76be1a49c4949012be8c33

```
Tests with failures:
  - com.tdunning.math.stats.MergingDigestTest.bigJump
  - com.tdunning.math.stats.AVLTreeDigestTest.bigJump
```

```
FAILURE 0.00s | AVLTreeDigestTest.bigJump <<<
   > Throwable #1: java.lang.AssertionError: expected:<0.925> but was:<0.975>
   > 	at __randomizedtesting.SeedInfo.seed([D177F9240078BD31:B29CA2C3E224C7A8]:0)
   > 	at org.junit.Assert.fail(Assert.java:93)
   > 	at org.junit.Assert.failNotEquals(Assert.java:647)
   > 	at org.junit.Assert.assertEquals(Assert.java:443)
   > 	at org.junit.Assert.assertEquals(Assert.java:512)
   > 	at com.tdunning.math.stats.TDigestTest.bigJump(TDigestTest.java:143)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

```
FAILURE 0.01s | MergingDigestTest.bigJump <<<
   > Throwable #1: java.lang.AssertionError: expected:<18.0> but was:<18.4789467368421>
   > 	at __randomizedtesting.SeedInfo.seed([D177F9240078BD31:379C5BDEB3A02ACB]:0)
   > 	at org.junit.Assert.fail(Assert.java:93)
   > 	at org.junit.Assert.failNotEquals(Assert.java:647)
   > 	at org.junit.Assert.assertEquals(Assert.java:443)
   > 	at org.junit.Assert.assertEquals(Assert.java:512)
   > 	at com.tdunning.math.stats.TDigestTest.bigJump(TDigestTest.java:156)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Any idea how to resolve these?

**Comment by tdunning** [comment]
To resolve these properly will take some analysis on my part, but I am
fairly sure that they are regression tests that don't represent anything
except as a flag to alert us to change and there has been a good bit of
that lately.

**Comment by tdunning** [comment]
Ah... to be specific, I am pretty sure you can ignore these failures for
now.

**Comment by tdunning** [comment]
This should be better as I clean up the tests headed for a release.
