### ISSUE TITLE
Latest changes do not work on some data (`AssertionError`)

### ISSUE THREAD

**Issue by excitoon** [tdunning/t-digest#167]
```
        MergingDigest d = new MergingDigest(100);
        d.add(9000, 2);
        d.add(3000, 5);
        d.add(3000, 6);
        d.add(1000, 10);
        d.add(1000, 16);
        System.out.println(d.quantile(0.9));
```

leads to:

```
java.lang.AssertionError
	at com.tdunning.math.stats.MergingDigest.merge(MergingDigest.java:489)
	at com.tdunning.math.stats.MergingDigest.mergeNewValues(MergingDigest.java:363)
	at com.tdunning.math.stats.MergingDigest.mergeNewValues(MergingDigest.java:353)
	at com.tdunning.math.stats.MergingDigest.quantile(MergingDigest.java:702)
```

We found this behavior while investigating ClickHouse/ClickHouse#22408 .

**Comment by tdunning** [comment]
Thanks. I will check this today.

**Comment by excitoon** [comment]
@tdunning BTW can you please also make some explanation about different results on the same data in weighted and unweighted versions:

On 3.2:
```
        MergingDigest d = new MergingDigest(100);
        int f = 1;
        d.add(9000, 2);
        d.add(3000, 5);
        d.add(3000, 6);
        d.add(1000, 10);
        d.add(1000, 16);
        System.out.println(d.quantile(0.9));
        System.out.println(d.quantile(0.95));
```
gives:
```
4650.000000000002
7574.999999999995
```

vs

```
        MergingDigest d = new MergingDigest(100);
        for (int i = 0; i < 2; ++i)
            d.add(9000);
        for (int i = 0; i < 11; ++i)
            d.add(3000);
        for (int i = 0; i < 26; ++i)
            d.add(1000);
        System.out.println(d.quantile(0.9));
        System.out.println(d.quantile(0.95));
```
gives:
```
3000.0
6299.999999999984
```

**Comment by tdunning** [comment]
The big problem with weighted add() is that you violate the t-digest
invariants. The weighted add() function is largely there to enable
serialization implementations.

I should note that this is another pressure to release the latest code as
soon as possible. WIth that code, the answers are exactly 3000 and 9000
because the handling of interpolation has been improved.

**Comment by filimonov** [comment]
One more test https://github.com/ClickHouse/ClickHouse/issues/32978
