### ISSUE TITLE
AssertionError if weight > 1

### ISSUE THREAD

**Issue by AlexanderSaydakov** [tdunning/t-digest#215]
```
@Test
public void rankOneValueWeight2() {
  TDigest td = TDigest.createDigest(100);
  td.add(1, 2);
  Assert.assertEquals(0, td.cdf(0.99), 0.0001);
  Assert.assertEquals(0.5, td.cdf(1), 0.0001);
  Assert.assertEquals(1, td.cdf(1.01), 0.0001);
}

```
java.lang.AssertionError
	at com.tdunning.math.stats.MergingDigest.merge(MergingDigest.java:489)
	at com.tdunning.math.stats.MergingDigest.mergeNewValues(MergingDigest.java:363)
	at com.tdunning.math.stats.MergingDigest.mergeNewValues(MergingDigest.java:353)
	at com.tdunning.math.stats.MergingDigest.cdf(MergingDigest.java:564)
	at com.tdunning.math.stats.MergingDigestTest2.rankOneValueWeight2(MergingDigestTest2.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by tdunning** [comment]
I think that what you are seeing here is that if you explicitly add a sample with weight greater than one, you can violate the t-digest invariant.

This is true and unavoidable. It is inherent in the use of a weight. The ability to enter samples with greater weight than unity is primarily there to allow easy deserialization, not for normal use.

**Comment by AlexanderSaydakov** [comment]
Are you saying that users should never call add() with weight != 1? If so, should there be one-parameter public add() and two-parameter private add()?

**Comment by tdunning** [comment]
Yes. Exactly.
