### ISSUE TITLE
MergingDigestTest fails on mvn test

### ISSUE THREAD

**Issue by gregakespret** [tdunning/t-digest#41]
After running `mvn test`, one test fails. This is the output:

```
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building T-Digest 3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ t-digest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/grega/Development/t-digest/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ t-digest ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ t-digest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/grega/Development/t-digest/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ t-digest ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ t-digest ---
[INFO] Surefire report directory: /Users/grega/Development/t-digest/target/surefire-reports
[INFO] parallel='methods', perCoreThreadCount=true, threadCount=1, useUnlimitedThreads=false, threadCountSuites=0, threadCountClasses=0, threadCountMethods=0

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.tdunning.math.stats.SortTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.144 sec - in com.tdunning.math.stats.SortTest
Running com.tdunning.math.stats.AVLGroupTreeTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.221 sec - in com.tdunning.math.stats.AVLGroupTreeTest
Running com.tdunning.math.stats.GroupTreeTest
0:0.0(1)	1:0.0(1)	2:1.0(1)	3:1.0(1)	4:2.0(1)	5:2.5(2)	6:3.0(1)	7:3.0(1)	8:4.0(1)	9:4.0(1)	10:5.0(1)	Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.083 sec - in com.tdunning.math.stats.GroupTreeTest
Running com.tdunning.math.stats.IntAVLTreeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.615 sec - in com.tdunning.math.stats.IntAVLTreeTest
Running com.tdunning.math.stats.TDigestTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.tdunning.math.stats.TDigestTest
Running com.tdunning.math.stats.AVLTreeDigestTest
# 19.501140us per point
# 794 centroids
Iteration 1# 15.788570us per point
# 851 centroids
# big 4491 bytes
# small 4491 bytes
# 15.375480us per point
# 843 centroids
# 53.819260us per point
# 4045 centroids
# 5.940800us per point
# 852 centroids
Start 0Start 1Start 2Finish 1Finish 2Finish 0Tests run: 20, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 67.329 sec - in com.tdunning.math.stats.AVLTreeDigestTest
Running com.tdunning.math.stats.ArrayDigestTest
# 19.488430us per point
# 838 centroids
# 25.380990us per point
# 842 centroids
# 18.371530us per point
# 841 centroids
# 15.674220us per point
# 854 centroids
# 5.107180us per point
# 866 centroids
# 4.435620us per point
# 858 centroids
# 3.549310us per point
# 865 centroids
# 4.670660us per point
# 854 centroids
# 4.219440us per point
# 833 centroids
# 4.117870us per point
# 853 centroids
# big 4438 bytes
# small 4438 bytes
# 44.124310us per point
# 732 centroids
# 26.484020us per point
# 781 centroids
# 21.444550us per point
# 778 centroids
Iteration 1# 21.182410us per point
# 847 centroids
# 126.478320us per point
# 3183 centroids
# 50.969960us per point
# 3195 centroids
# 35.860900us per point
# 3219 centroids
0.0	0.0000.1	0.0970.2	0.1990.3	0.3100.4	0.4060.5	0.4970.6	0.6170.7	0.7170.8	0.8130.9	0.9151.0	0.999# 25.518120us per point
# 843 centroids
Start 1Start 0Start 2Finish 0Finish 1Finish 2Tests run: 22, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 116.769 sec - in com.tdunning.math.stats.ArrayDigestTest
Running com.tdunning.math.stats.MergingDigestTest
# 30.942950us per point
# 443 centroids
# 28.387310us per point
# 318 centroids
# big 4576 bytes
# small 4576 bytes
# 41.353910us per point
# 4045 centroids
# 28.407520us per point
# 314 centroids
Start 0Start 1Start 2Finish 0Finish 2Finish 1Tests run: 20, Failures: 0, Errors: 3, Skipped: 1, Time elapsed: 59.454 sec <<< FAILURE! - in com.tdunning.math.stats.MergingDigestTest
testMerge(com.tdunning.math.stats.MergingDigestTest)  Time elapsed: 3.628 sec  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<100000> but was:<69>
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at com.tdunning.math.stats.TDigestTest.merge(TDigestTest.java:179)
	at com.tdunning.math.stats.MergingDigestTest.testMerge(MergingDigestTest.java:477)
Caused by: java.lang.AssertionError: expected:<100000> but was:<69>
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.Assert.failNotEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:126)
	at org.junit.Assert.assertEquals(Assert.java:470)
	at org.junit.Assert.assertEquals(Assert.java:454)
	at com.tdunning.math.stats.TDigestTest$1.call(TDigestTest.java:145)
	at com.tdunning.math.stats.TDigestTest$1.call(TDigestTest.java:91)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

testNarrowNormal(com.tdunning.math.stats.MergingDigestTest)  Time elapsed: 0.073 sec  <<< ERROR!
java.lang.NullPointerException: null
	at com.tdunning.math.stats.MergingDigest.mergeNewValues(MergingDigest.java:148)
	at com.tdunning.math.stats.MergingDigest.add(MergingDigest.java:118)
	at com.tdunning.math.stats.AbstractTDigest.add(AbstractTDigest.java:154)
	at com.tdunning.math.stats.TDigestTest.runTest(TDigestTest.java:268)
	at com.tdunning.math.stats.MergingDigestTest.testNarrowNormal(MergingDigestTest.java:108)

testSorted(com.tdunning.math.stats.MergingDigestTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NullPointerException: null

Running com.tdunning.math.stats.TreeDigestTest
# 22.434220us per point
# 749 centroids
# 12.782380us per point
# 834 centroids
# big 4464 bytes
# small 4464 bytes
Iteration 1# 12.420250us per point
# 824 centroids
# 96.659150us per point
# 4700 centroids
# 11.418890us per point
# 847 centroids
Start 0Start 1Start 2Finish 2Finish 1Finish 0Tests run: 20, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 85.281 sec - in com.tdunning.math.stats.TreeDigestTest

Results :

Tests in error: 
  MergingDigestTest.testMerge:477->TDigestTest.merge:179 ? Execution java.lang.A...
  MergingDigestTest.testNarrowNormal:108->TDigestTest.runTest:268 ? NullPointer
  MergingDigestTest.testSorted ? NullPointer

Tests run: 103, Failures: 0, Errors: 3, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:04 min
[INFO] Finished at: 2015-03-14T11:45:54+01:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project t-digest: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/grega/Development/t-digest/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project t-digest: There are test failures.

Please refer to /Users/grega/Development/t-digest/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /Users/grega/Development/t-digest/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:82)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:190)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:852)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:720)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by gregakespret** [comment]
Environment info:

```
$ mvn -version
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T15:51:42+02:00)
Maven home: /usr/local/Cellar/maven/3.2.2/libexec
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: US-ASCII
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
```

**Comment by tdunning** [comment]
Yes.  I destabilized things a bit by introducing MergingDigest.  Working to restabilize.

I will push an interim step today.  Still partially broken, but less so.

**Comment by tdunning** [comment]
Still broken as I noted it would be.  But improving.

https://travis-ci.org/tdunning/t-digest/builds/54462308

**Comment by gregakespret** [comment]
It seems to be fixed now.
