### ISSUE TITLE
Getting IllegalArgumentException when adding digests

### ISSUE THREAD

**Issue by tomdz** [tdunning/t-digest#60]
I'm using Spark to build a bunch of AVLTreeDigests, one for each partition of the data. All digests are initialized with compression 100, and values are all added with weight 1. When I then try to add these partition digests I get this exception:

```
java.lang.IllegalArgumentException
    at com.tdunning.math.stats.AVLTreeDigest.add(AVLTreeDigest.java:60)
    at com.tdunning.math.stats.AbstractTDigest.add(AbstractTDigest.java:166)
    at test.TDigestWrapper.$plus(TestDigest.scala:34)
    at test.DigestAccumulatorParam.addInPlace(TestDigest.scala:42)
    at test.DigestAccumulatorParam.addInPlace(TestDigest.scala:41)
    at org.apache.spark.Accumulable.$plus$plus$eq(Accumulators.scala:80)
    at org.apache.spark.Accumulators$$anonfun$add$2.apply(Accumulators.scala:342)
    at org.apache.spark.Accumulators$$anonfun$add$2.apply(Accumulators.scala:337)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
    at org.apache.spark.Accumulators$.add(Accumulators.scala:337)
    at org.apache.spark.scheduler.DAGScheduler.updateAccumulators(DAGScheduler.scala:945)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:1014)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1454)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1418)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
```

The two digests in question seem to be empty actually, but with different centroids. The accumulator one has an empty centroids array whereas the other digest has a single centroid `Centroid{centroid=NaN, count=0}`. That latter one was deserialized via `AVLTreeDigest.fromBytes`.

**Comment by tdunning** [comment]
Tom,

I am trying to close out issues like this.

Did you resolve this issue (in the looong time it took me to get back to you)? Does 3.2-SNAPSHOT resolve it?

Do you have a simple test case that shows this?

**Comment by tdunning** [comment]
Closing as WORKS_FOR_ME
